@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BorderColor #666
  BackgroundColor #F7F7FF
}


actor User
actor Author


Author --|> User

rectangle "Quiz System" as System {
  usecase (Register) as UC_Register
  usecase (Manage profile) as UC_Profile
  usecase (Change avatar) as UC_ChangeAvatar
  usecase (Change username) as UC_ChangeUsername
  usecase (Change password) as UC_ChangePassword
  usecase (Send Confirmation Email) as UC_SendConfirm
  usecase (Send Password Reset Link) as UC_SendReset


  usecase (Create test) as UC_CreateTest
  usecase (Manage test) as UC_ManageTest
  usecase (Add questions) as UC_AddQuestions
  usecase (Add question with single answer) as UC_QuestSingle
  usecase (Add question with multiple answers) as UC_QuestMultiple
  usecase (Add question with free text) as UC_QuestFree
  usecase (Add question with relevance) as UC_QuestRel
  usecase (Add answer options) as UC_AddOptions
  usecase (Edit question) as UC_EditQuestion
  usecase (Delete question) as UC_DeleteQuestion
  usecase (Edit test details) as UC_EditTestDetails
  usecase (Delete test) as UC_DeleteTest
  usecase (Find test) as UC_FindTest



  usecase (Take a test) as UC_TakeTest
  usecase (Answer the question) as UC_Answer
  usecase (Answer with single answer) as UC_AnsSingle
  usecase (Answer with multiple answers) as UC_AnsMulti
  usecase (Answer with free text) as UC_AnsFree
  usecase (Answer with relevance) as UC_AnsRel
  usecase (View your results) as UC_ViewMyResults
  usecase (View result of all tests) as UC_ViewAllResults


  usecase (Rate test) as UC_RateTest
  usecase (Write text review) as UC_WriteReview
  usecase (View review) as UC_ViewReview
  usecase (Bookmark test) as UC_Bookmark
  usecase (View bookmarked tests) as UC_ViewBookmarks
  usecase (View quiz stats) as UC_ViewStats
}


User --> UC_Register
User --> UC_Profile
User --> UC_FindTest
User --> UC_TakeTest
User --> UC_ViewMyResults
User --> UC_RateTest
User --> UC_ViewReview
User --> UC_Bookmark
User --> UC_ViewBookmarks
User --> UC_ViewAllResults

Author --> UC_CreateTest
Author --> UC_ManageTest
Author --> UC_AddQuestions
Author --> UC_AddOptions
Author --> UC_ViewStats


UC_Register .> UC_SendConfirm : <<include>>
UC_ChangePassword .> UC_SendReset : <<include>>

UC_TakeTest .> UC_FindTest : <<include>>
UC_FindTest .> UC_CreateTest : <<include>>
UC_CreateTest .> UC_ManageTest : <<include>>
UC_ViewStats .> UC_CreateTest : <<include>>
UC_ManageTest .> UC_AddQuestions : <<include>>
UC_EditTestDetails .> UC_ManageTest : <<extend>>
UC_DeleteTest .> UC_ManageTest : <<extend>>
UC_EditQuestion .> UC_ManageTest : <<extend>>
UC_DeleteQuestion .> UC_ManageTest : <<extend>>
UC_QuestSingle .> UC_AddQuestions : <<extend>>
UC_QuestMultiple .> UC_AddQuestions : <<extend>>
UC_QuestFree .> UC_AddQuestions : <<extend>>
UC_QuestRel .> UC_AddQuestions : <<extend>>
UC_AddQuestions .> UC_AddOptions : <<include>>
UC_ChangeAvatar .> UC_Profile: <<extend>>
UC_ChangeUsername .> UC_Profile: <<extend>>
UC_ChangePassword .> UC_Profile: <<extend>>
UC_WriteReview .> UC_RateTest: <<extend>>
UC_RateTest .> UC_FindTest: <<include>>
UC_ViewReview .> UC_FindTest: <<include>>
UC_ViewMyResults .> UC_TakeTest: <<extend>>
UC_TakeTest .> UC_Answer : <<include>>
UC_AnsSingle .> UC_Answer : <<extend>>
UC_AnsMulti .> UC_Answer : <<extend>>
UC_AnsFree .> UC_Answer : <<extend>>
UC_AnsRel .> UC_Answer : <<extend>>
UC_Bookmark .> UC_FindTest : <<include>>



@enduml
